"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Tabs, Tab, Box, Typography, Divider } from "@mui/material";
import Image from "next/image";

// Define Tab Indexes Enum
enum TabIndex {
  PANELS = 0,
  ELECTRONICS = 1,
  BATTERIES = 2,
}

const SolarComponents: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabIndex>(TabIndex.PANELS);

  const handleTabChange = (event: React.SyntheticEvent, newValue: TabIndex) => {
    setActiveTab(newValue);
  };

  return (
    <Box sx={{ py: 6, textAlign: "center" }}>
      <Typography variant="h4" fontWeight="bold">
        Best Solar <span style={{ color: "#FFCC00" }}>Components</span>
      </Typography>

      <Tabs
        value={activeTab}
        onChange={handleTabChange}
        centered
        sx={{
          mt: 3,
          mb: 2,
          "& .MuiTabs-indicator": { backgroundColor: "blue" },
        }}
      >
        <Tab label="Panels" value={TabIndex.PANELS} />
        <Tab label="Electronics" value={TabIndex.ELECTRONICS} />
        <Tab label="Batteries" value={TabIndex.BATTERIES} />
      </Tabs>

      <Divider sx={{ mb: 3, width: "80%", mx: "auto" }} />

      <Box sx={{ px: { xs: 2, md: 6 } }}>
        {activeTab === TabIndex.PANELS && <Panels />}
        {activeTab === TabIndex.ELECTRONICS && <Electronics />}
        {activeTab === TabIndex.BATTERIES && <Batteries />}
      </Box>
    </Box>
  );
};

// Panels Component
const Panels: React.FC = () => (
  <motion.div
    initial={{ opacity: 0, x: -50 }}
    animate={{ opacity: 1, x: 0 }}
    transition={{ duration: 0.8 }}
  >
    <Typography variant="h5" fontWeight="bold">
      Best Solar <span style={{ color: "#FFCC00" }}>Panels Online</span>
    </Typography>
    <Typography variant="body1" sx={{ mt: 2 }}>
      While most of us think of solar power as a recent innovation, it has been
      advancing for longer than a century...
    </Typography>

    <Image
      src="/solar/solar4.jpg"
      alt="Solar Panels"
      width={600}
      height={400}
      style={{ marginTop: "20px", borderRadius: "10px" }}
    />

    <Typography variant="h6" sx={{ mt: 3, fontWeight: "bold" }}>
      What is Solar Power & How Does It Work?
    </Typography>
    <Typography variant="body2">
      The sun produces 4,000,000 tons of energy every second, enough to power
      our planet for billions of years...
    </Typography>
  </motion.div>
);

// Electronics Component
const Electronics: React.FC = () => (
  <motion.div
    initial={{ opacity: 0, x: 50 }}
    animate={{ opacity: 1, x: 0 }}
    transition={{ duration: 0.8 }}
  >
    <Typography variant="h5" fontWeight="bold">
      Solar Electronics:{" "}
      <span style={{ color: "#FFCC00" }}>Off-Grid & On-Grid Inverters</span>
    </Typography>
    <Typography variant="body1" sx={{ mt: 2 }}>
      A solar power system has several key components, including panels,
      inverters, batteries, and connectors...
    </Typography>

    <Image
      src="/solar/solar5.jpg"
      alt="Solar Inverter"
      width={600}
      height={400}
      style={{ marginTop: "20px", borderRadius: "10px" }}
    />

    <Typography variant="h6" sx={{ mt: 3, fontWeight: "bold" }}>
      Types of Solar Inverters
    </Typography>
    <Typography variant="body2">
      There are three major types of solar inverters: Grid-Tie, Off-Grid, and
      Hybrid.
    </Typography>
  </motion.div>
);

// Batteries Component
const Batteries: React.FC = () => (
  <motion.div
    initial={{ opacity: 0, x: -50 }}
    animate={{ opacity: 1, x: 0 }}
    transition={{ duration: 0.8 }}
  >
    <Typography variant="h5" fontWeight="bold">
      Solar <span style={{ color: "#FFCC00" }}>Batteries</span> for Energy
      Storage
    </Typography>
    <Typography variant="body1" sx={{ mt: 2 }}>
      Apart from inverters, batteries are essential for storing electricity
      generated by solar power systems...
    </Typography>

    <Image
      src="/solar/solar3.jpg"
      alt="Solar Battery"
      width={600}
      height={400}
      style={{ marginTop: "20px", borderRadius: "10px" }}
    />

    <Typography variant="h6" sx={{ mt: 3, fontWeight: "bold" }}>
      Why Choose the Right Battery?
    </Typography>
    <Typography variant="body2">
      The right solar battery ensures better efficiency and longevity of your
      solar setup.
    </Typography>
  </motion.div>
);

export default SolarComponents;
